Add improved search command
AY2122S1-CS2103T-T17-3/tp pull request #41
Opened 2021-10-03 13:04 UTC by wyrchris

### Description

Added Search Command along with respective Parser class and Predicate class to update Model with search result. ArgumentMultiMap class has also been updated to allow for proper equality check.

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] Code quality improvements

### Checklist
- [X] I have tested this code
- [X] I have updated the documentation

Closes #12

2021-10-05 16:27 UTC, CrownKira requested changes
Nice~

2021-10-05 16:27 UTC, CrownKira commented on docs/UserGuide.md
> +* The search is case-insensitive. e.g `keith` will match `Keith`.
It is not case-insensitive: `search Serangoon` works but not `search serangoon`

2021-10-05 16:27 UTC, CrownKira commented on docs/UserGuide.md
> +* `create Keith email/keithtan@ymail.com phone-no/12345678 risk-appetite/4`
The current implementation doesn't support full prefix email/, perhaps you should change this back to e/ (update this again in future PR when this is supported)

2021-10-05 16:27 UTC, CrownKira commented on docs/UserGuide.md
> +* `create Keith email/keithtan@ymail.com phone-no/12345678 risk-appetite/4`
OR perhaps you want to create an issue on this

2021-10-05 17:25 UTC, wyrchris commented on docs/UserGuide.md
> +* The search is case-insensitive. e.g `keith` will match `Keith`.
Have committed change to make the search case insensitive

2021-10-05 17:29 UTC, wyrchris commented on docs/UserGuide.md
> +* `create Keith email/keithtan@ymail.com phone-no/12345678 risk-appetite/4`
The current version of the user guide is already using this new syntax and the implementation of these prefix if I am not wrong will be done under the updating of client info

2021-10-06 01:11 UTC, CrownKira approved these changes
Seems to work. LGTM!

2021-10-06 01:11 UTC, merged